name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  ga-test:
    runs-on: ubuntu-latest
    steps:
      - id: fail
        run: exit 0
      - if: always() && steps.fail.outcome == 'failure'
        run: echo "I'm still running"
